version: '3.3'

services:

  fireflyiii:
    image: fireflyiii/core:latest
    container_name: firefly
    restart: unless-stopped
    volumes:
      - ./firefly_upload:/var/www/html/storage/upload 
    env_file: .env
    ports:
      - "8200:8080"
    depends_on:
      - db
      
  db:
    image: yobasystems/alpine-mariadb    
    container_name: firefly-db
    restart: unless-stopped  
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=firefly_contraseña
      - MYSQL_DATABASE=firefly
    volumes:
      - ./firefly_db:/var/lib/mysql

   
